name: Notifications App Build and Test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package  # --quiet

      - name: Set up MongoDB service
        uses: supercharge/mongodb-github-action@1.8.0

      - name: Run tests
        run: mvn test  # --quiet

      - name: Create release
        uses: actions/create-release@v1
        env:
              GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
                tag_name: ${{ steps.bump_version.outputs.nextRelease.version }}
                release_name: Release ${{ steps.bump_version.outputs.nextRelease.version }}
                draft: false
                prerelease: false