name: Notifications App Build and Test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package  # --quiet

      - name: Set up MongoDB service
        uses: supercharge/mongodb-github-action@1.8.0

      - name: Run tests
        run: mvn test  # --quiet